apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations: 
    metallb.universe.tf/allow-shared-ip: inside
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: 80
  - port: 443
    protocol: TCP
    name: https
    targetPort: 443
  - port: 22
    protocol: TCP
    name: ssh
    targetPort: 22
  selector:
    app: nginx
  type: LoadBalancer
