apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations: 
    metallb.universe.tf/allow-shared-ip: inside
spec:
  ports:
  - port: 5050
    protocol: TCP
    name: wordpress
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer